In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.4.1'

In [4]:
dataset = pd.read_excel('Churn-Modelling.xlsx')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
dataset.shape

(10000, 14)

In [7]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)

[1 0 1 ... 1 1 0]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [15]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
ann = tf.keras.models.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 468us/step - loss: 0.6616 - accuracy: 0.6124
Epoch 2/100
250/250 [==============================] - 0s 445us/step - loss: 0.4874 - accuracy: 0.7976
Epoch 3/100
250/250 [==============================] - 0s 445us/step - loss: 0.4537 - accuracy: 0.7985
Epoch 4/100
250/250 [==============================] - 0s 469us/step - loss: 0.4346 - accuracy: 0.8045
Epoch 5/100
250/250 [==============================] - 0s 443us/step - loss: 0.4112 - accuracy: 0.8218
Epoch 6/100
250/250 [==============================] - 0s 453us/step - loss: 0.4114 - accuracy: 0.8279
Epoch 7/100
250/250 [==============================] - 0s 473us/step - loss: 0.4109 - accuracy: 0.8207
Epoch 8/100
250/250 [==============================] - 0s 465us/step - loss: 0.3970 - accuracy: 0.8298
Epoch 9/100
250/250 [==============================] - 0s 473us/step - loss: 0.3853 - accuracy: 0.8352
Epoch 10/100
250/250 [==============================] - 0s 453us/step - l

250/250 [==============================] - 0s 449us/step - loss: 0.3371 - accuracy: 0.8577
Epoch 80/100
250/250 [==============================] - 0s 457us/step - loss: 0.3324 - accuracy: 0.8604
Epoch 81/100
250/250 [==============================] - 0s 445us/step - loss: 0.3329 - accuracy: 0.8613
Epoch 82/100
250/250 [==============================] - 0s 449us/step - loss: 0.3195 - accuracy: 0.8640
Epoch 83/100
250/250 [==============================] - 0s 445us/step - loss: 0.3287 - accuracy: 0.8667
Epoch 84/100
250/250 [==============================] - 0s 453us/step - loss: 0.3260 - accuracy: 0.8628
Epoch 85/100
250/250 [==============================] - 0s 449us/step - loss: 0.3333 - accuracy: 0.8633
Epoch 86/100
250/250 [==============================] - 0s 453us/step - loss: 0.3313 - accuracy: 0.8638
Epoch 87/100
250/250 [==============================] - 0s 441us/step - loss: 0.3335 - accuracy: 0.8601
Epoch 88/100
250/250 [==============================] - 0s 453us/step - loss:

In [23]:
y_pred = ann.predict(X_test)
y_pred

array([[0.3522582 ],
       [0.3478589 ],
       [0.17053291],
       ...,
       [0.20157096],
       [0.32336617],
       [0.23779115]], dtype=float32)

In [24]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [25]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1501   94]
 [ 173  232]]


In [27]:
accuracy  =  (1534 + 200)/(1534 + 61+ 205 + 200)
accuracy

0.867

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8665